### ISSUE TITLE
How does this work without Android.mk

### ISSUE THREAD

**Issue by kewp** [tsaarni/android-native-egl-example#6]
This isn't an issue, just a question - I'm studying using the using the NDK and JNI and typically you need an Android.mk file in the jni directory (or now a CMakeList.txt) but your project has none ! How does it work ?!

I can't find documentation anywhere. Are there standard filenames / paths for NDK libs ?

**Comment by tsaarni** [comment]
Yes, Gradle NDK integration builds native code under src/main/jni by default, see
http://tools.android.com/tech-docs/new-build-system/gradle-experimental#TOC-Ndk-Integration
